# Here CURDIR is assumed to be the root folder of the project.

CARLA_ROOT_FOLDER=${CURDIR}
CARLA_BUILD_FOLDER=${CURDIR}/lib

LIBCARLA_ROOT_FOLDER=${CURDIR}/src/libcarla


CMAKE_CONFIG_FILE=${CARLA_BUILD_FOLDER}/CMakeLists.txt.in

LIBCARLA_TEST_CONTENT_FOLDER=${CARLA_BUILD_FOLDER}/test-content

# libcarla variables

LIBCARLA_BUILD_PATH=${CURDIR}/build
LIBCARLA_LIB_INSTALL_PATH=${CURDIR}
LIBCARLA_HEADER_INSTALL_PATH=${CURDIR}
LIBCARLA_BUILD_TOOLCHAIN=${CURDIR}/lib/Toolchain.cmake