name: CarlaViz Docker Depolyment
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'  # semantic version

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t carlaviz:${{ github.ref_name }} .
    - name: Push image
      run: docker push carlaviz:${{ github.ref_name }}
