name: CarlaViz Docker Depolyment
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'   # semantic version
    - '[0-9]+.[0-9]+.[0-9]+.[0-9]+.'
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image on Tag
      if: github.ref != 'refs/heads/master'
      run: docker build -t mjxu96/carlaviz:${{ github.ref_name }} .
    - name: Push image on Tag
      if: github.ref != 'refs/heads/master'
      run: docker push mjxu96/carlaviz:${{ github.ref_name }}
    - name: Build Docker image on Master
      if: github.ref == 'refs/heads/master'
      run: docker build -t mjxu96/carlaviz:latest .
    - name: Push image on Master
      if: github.ref == 'refs/heads/master'
      run: docker push mjxu96/carlaviz:latest
